### ISSUE TITLE
改良案 小数点も入力できるようにするといいかも

### ISSUE THREAD

**Issue by stak** [Tsubasa-Sato/BMI#3]
今の実装だと、整数の値しか正しく受けつけてくれないかと思います。
それを、小数でも入力できるようにすると勉強になるかもしれません。

今は、

``` js
if (weight.match(/^[1-9][0-9]*$/) && told.match(/^[1-9][0-9]*$/)){
```

という正規表現を使った条件式で、入力された内容が正しいかみているようなので、
ここの正規表現を変えることで、小数も OK にできますね。

別の方法としては、文字列の値から、数値の値に変換する js 組み込みの関数を使う方法があります。

文字列を整数にする関数 parseInt
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/parseInt

文字列を小数にする関数 parseFloat
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/parseFloat

このあたりを参考にしてみてください。
なお、これらの関数を使うと、もとの文字列が正しく数値にできないものだった場合、[NaN という特別な値](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/NaN)が返ります。

ですので、こちらの方法なら上記の正規表現は不要となり、

``` js
weight = parseFloat(weight);
told = parseFloat(told);
if (weight > 0 && told > 0) {
    // いろいろ
}
```

みたいに書くとスッキリするかなと思います。

**Comment by Tsubasa-Sato** [comment]
改良点を教えてくださりありがとうございます。やってみようと思います。

**Comment by stak** [comment]
https://github.com/Tsubasa-Sato/BMI/commit/4d3fc76727094a03eb76cfb82f8bca74f2eacba4

↑確認しましたー。いいと思います :+1:
